name: Bust Cloudflare Cache

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Bust Cloudflare Cache
    steps:
      - name: Bust Cloudflare Cache
        uses: spring-io/spring-doc-actions/bust-cloudflare-antora-cache@v0.0.20
        with:
          context-root: spring-shell
          cloudflare-zone-id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          cloudflare-cache-token: ${{ secrets.CLOUDFLARE_CACHE_TOKEN }}
