name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    name: CI Build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -DaltDeploymentRepository=local::file:deployment-repository --no-transfer-progress --batch-mode --update-snapshots deploy

      - name: Deploy to Artifactory
        if: ${{ github.repository == 'spring-projects/spring-shell' && github.ref_name == 'main' }}
        uses: spring-io/artifactory-deploy-action@v0.0.2
        with:
          uri: 'https://repo.spring.io'
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          build-name: 'spring-shell-main'
          repository: 'libs-snapshot-local'
          folder: 'deployment-repository'
          signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
          signing-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Generate Java docs
        run: ./mvnw --no-transfer-progress javadoc:aggregate

      - name: Generate Reference docs
        working-directory: spring-shell-docs
        run: ../mvnw --no-transfer-progress resources:resources antora

      - name: Setup SSH key
        env:
          DOCS_SSH_KEY: ${{ secrets.DOCS_SSH_KEY }}
          DOCS_SSH_HOST_KEY: ${{ secrets.DOCS_SSH_HOST_KEY }}
        run: |
          mkdir "$HOME/.ssh"
          echo "$DOCS_SSH_KEY" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          echo "$DOCS_SSH_HOST_KEY" > "$HOME/.ssh/known_hosts"

      - name: Capture project version
        run: echo PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version --quiet -DforceStdout) >> $GITHUB_ENV

      - name: Deploy docs
        env:
          DOCS_HOST: ${{ secrets.DOCS_HOST }}
          DOCS_USERNAME: ${{ secrets.DOCS_USERNAME }}
          DOCS_PATH: /opt/www/domains/spring.io/docs/htdocs/spring-shell
        run: |
          ssh -i $HOME/.ssh/key $DOCS_USERNAME@$DOCS_HOST "cd $DOCS_PATH/docs && mkdir -p $PROJECT_VERSION"
          scp -i $HOME/.ssh/key -r target/reports/apidocs $DOCS_USERNAME@$DOCS_HOST:$DOCS_PATH/docs/$PROJECT_VERSION/api
          
          ssh -i $HOME/.ssh/key $DOCS_USERNAME@$DOCS_HOST "cd $DOCS_PATH/reference && mkdir -p $PROJECT_VERSION"
          scp -i $HOME/.ssh/key -r spring-shell-docs/target/site/shell/$PROJECT_VERSION $DOCS_USERNAME@$DOCS_HOST:$DOCS_PATH/reference/$PROJECT_VERSION

      - name: Bust Cloudflare Cache
        uses: spring-io/spring-doc-actions/bust-cloudflare-antora-cache@v0.0.20
        with:
          context-root: spring-shell
          cloudflare-zone-id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          cloudflare-cache-token: ${{ secrets.CLOUDFLARE_CACHE_TOKEN }}
