name: Documentation Upload

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Capture release version
        run: echo RELEASE_VERSION=${{ github.event.inputs.releaseVersion }} >> $GITHUB_ENV

      - name: Checkout source code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Capture project version
        run: echo PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version --quiet -DforceStdout) >> $GITHUB_ENV

      - name: Update release version
        run: |
          ./mvnw versions:set -DgenerateBackupPoms=false -DnewVersion=$RELEASE_VERSION
          sed -i "s/version: $PROJECT_VERSION/version: $RELEASE_VERSION/" spring-shell-docs/antora.yml

      - name: Setup SSH key
        env:
          DOCS_SSH_KEY: ${{ secrets.DOCS_SSH_KEY }}
          DOCS_SSH_HOST_KEY: ${{ secrets.DOCS_SSH_HOST_KEY }}
        run: |
          mkdir "$HOME/.ssh"
          echo "$DOCS_SSH_KEY" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          echo "$DOCS_SSH_HOST_KEY" > "$HOME/.ssh/known_hosts"

      - name: Generate Java docs
        run: ./mvnw --no-transfer-progress javadoc:aggregate

      - name: Deploy Java docs
        env:
          DOCS_HOST: ${{ secrets.DOCS_HOST }}
          DOCS_USERNAME: ${{ secrets.DOCS_USERNAME }}
          DOCS_PATH: /opt/www/domains/spring.io/docs/htdocs/spring-shell
        run: |
          ssh -i $HOME/.ssh/key $DOCS_USERNAME@$DOCS_HOST "cd $DOCS_PATH/docs && mkdir -p $RELEASE_VERSION"
          scp -i $HOME/.ssh/key -r target/reports/apidocs $DOCS_USERNAME@$DOCS_HOST:$DOCS_PATH/docs/$RELEASE_VERSION/api

      - name: Generate Reference docs
        working-directory: spring-shell-docs
        run: ../mvnw --no-transfer-progress resources:resources antora

      - name: Deploy Reference docs
        env:
          DOCS_HOST: ${{ secrets.DOCS_HOST }}
          DOCS_USERNAME: ${{ secrets.DOCS_USERNAME }}
          DOCS_PATH: /opt/www/domains/spring.io/docs/htdocs/spring-shell
        run: |
          ssh -i $HOME/.ssh/key $DOCS_USERNAME@$DOCS_HOST "cd $DOCS_PATH/reference && mkdir -p $RELEASE_VERSION"
          scp -i $HOME/.ssh/key -r spring-shell-docs/target/site/shell/$RELEASE_VERSION $DOCS_USERNAME@$DOCS_HOST:$DOCS_PATH/reference/$RELEASE_VERSION

      - name: Bust Cloudflare Cache
        uses: spring-io/spring-doc-actions/bust-cloudflare-antora-cache@v0.0.20
        with:
          context-root: spring-shell
          cloudflare-zone-id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          cloudflare-cache-token: ${{ secrets.CLOUDFLARE_CACHE_TOKEN }}